# Generated by Django 3.2.6 on 2021-08-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykagora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Game_content')),
            ],
        ),
        migrations.RemoveField(
            model_name='agoraroom',
            name='profile1',
        ),
        migrations.RemoveField(
            model_name='agoraroom',
            name='profile2',
        ),
        migrations.DeleteModel(
            name='Agora',
        ),
        migrations.DeleteModel(
            name='Agoraroom',
        ),
    ]
