# Generated by Django 3.2.5 on 2021-07-17 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=50, verbose_name='관심사')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='전화번호')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='닉네임')),
                ('school', models.CharField(blank=True, max_length=20, null=True, verbose_name='학교')),
                ('block_school', models.BooleanField(blank=True, default=False, null=True, verbose_name='학교 안보이기')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='나이')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='성별')),
                ('goal', models.CharField(blank=True, max_length=100, null=True, verbose_name='목표')),
                ('major', models.CharField(blank=True, max_length=50, null=True, verbose_name='전공')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='자기 소개')),
                ('mbti', models.CharField(blank=True, max_length=50, null=True, verbose_name='mbti')),
                ('club', models.CharField(blank=True, max_length=150, null=True, verbose_name='동아리')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소')),
                ('follower', models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('interest', models.ManyToManyField(blank=True, related_name='interests', to='yk.Interest')),
                ('today_friends', models.ManyToManyField(blank=True, related_name='today_friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('user_report', models.ManyToManyField(blank=True, related_name='user_report', to=settings.AUTH_USER_MODEL)),
                ('yesterday_friends', models.ManyToManyField(blank=True, related_name='yesterday_friends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
