# Generated by Django 3.2.5 on 2021-07-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0005_alter_letter_network_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
