# Generated by Django 3.2.5 on 2021-07-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0006_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='ask_from',
        ),
        migrations.RemoveField(
            model_name='ask',
            name='ask_report',
        ),
        migrations.RemoveField(
            model_name='ask',
            name='ask_to',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='today_friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='yesterday_friends',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Ask',
        ),
    ]
