# Generated by Django 3.2.5 on 2021-07-28 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yk', '0007_auto_20210728_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='unseen_to',
            field=models.ManyToManyField(blank=True, related_name='my_unseen', to=settings.AUTH_USER_MODEL),
        ),
    ]
