# Generated by Django 3.2.5 on 2021-07-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0008_letter_unseen_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isOnCall',
            field=models.BooleanField(default=False),
        ),
    ]
