# Generated by Django 3.2.5 on 2021-07-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0009_profile_isoncall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isOnCall',
        ),
    ]
