# Generated by Django 3.2.5 on 2021-07-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0011_interest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
    ]
