# Generated by Django 3.2.5 on 2021-08-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0012_remove_interest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interest',
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.TextField(blank=True, null=True, verbose_name='자기 소개'),
        ),
    ]
