# Generated by Django 3.2.5 on 2021-08-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0013_auto_20210801_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.TextField(blank=True, null=True, verbose_name='관심사'),
        ),
    ]
