# Generated by Django 3.2.5 on 2021-08-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
