# Generated by Django 3.2.6 on 2021-08-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0018_want_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='want_gender',
            old_name='gender',
            new_name='want_gender',
        ),
    ]
