# Generated by Django 3.2.6 on 2021-08-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0019_rename_gender_want_gender_want_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='want_gender',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='성별'),
        ),
        migrations.DeleteModel(
            name='Want_gender',
        ),
    ]
