# Generated by Django 3.2.6 on 2021-08-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0021_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.TextField(blank=True, null=True, verbose_name='나이'),
        ),
    ]
