# Generated by Django 3.2.6 on 2021-08-24 08:10

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0022_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
