# Generated by Django 3.2.6 on 2021-08-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0023_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agree',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agree',
            name='agree',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
