# Generated by Django 3.2.6 on 2021-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0024_auto_20210827_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agree',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
