# Generated by Django 3.2.6 on 2021-08-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0025_alter_agree_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agree',
            name='created_at',
        ),
    ]
