# Generated by Django 3.2.6 on 2021-08-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0027_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_img',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
