# Generated by Django 3.2.6 on 2021-09-02 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yk', '0028_school_img_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter_network',
            name='push_on',
            field=models.ManyToManyField(blank=True, default=None, related_name='push_on', to=settings.AUTH_USER_MODEL),
        ),
    ]
