# Generated by Django 3.2.6 on 2021-09-03 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0029_letter_network_push_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter_network',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 1, 1, 18, 184576)),
        ),
    ]
